language: node_js
node_js:
  - "7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs npm python3 python3-pip
  - sudo pip3 install schul-cloud-search-tests

install:
  - npm install

script:
  - npm test

